/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.Estado_Civil;

import com.mycompany.Ferramentas.Constantes;
import com.mycompany.Ferramentas.DadosTemporarios;
import com.mycompany.Ferramentas.Formularios;
import com.mycompany.Modelo.ModEstado_Civil;
import com.mycompany.Dao.DaoEstadoCivil;
import com.mycompany.visao.Pais.ListPais;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo.3946
 */
public class CadEstado_Civil extends javax.swing.JFrame {

    /**
     * Creates new form CadEstado_Civil1
     */
    public CadEstado_Civil() {
        initComponents();
        
        if(!existeDadosTemporarios()){
            DaoEstadoCivil daoEstado_Civil = new DaoEstadoCivil();

            int id = daoEstado_Civil.buscarProximoId(); 
            if (id >= 0)
                TFid.setText(String.valueOf(id));
            
            BTacao.setText(Constantes.BTN_SALVAR_TEXT);
            BTexcluir.setVisible(false);
        }else{
            BTacao.setText(Constantes.BTN_ALTERAR_TEXT);
            BTexcluir.setVisible(true);
        }
        
        setLocationRelativeTo(null);
        
        TFid.setEnabled(false);
    }

    private Boolean existeDadosTemporarios(){        
        if(DadosTemporarios.tempObject instanceof ModEstado_Civil){
            int id = ((ModEstado_Civil) DadosTemporarios.tempObject).getId();
            String nome = ((ModEstado_Civil) DadosTemporarios.tempObject).getNome();
            
            TFid.setText(String.valueOf(id));
            TFnome.setText(nome);
            
            DadosTemporarios.tempObject = null;
            
            return true;
        }else
            return false;
    }
    
    private void inserir(){
        DaoEstadoCivil daoEstado_Civil = new DaoEstadoCivil();
        
        if (daoEstado_Civil.inserir(Integer.parseInt(TFid.getText()), TFnome.getText())){
            JOptionPane.showMessageDialog(null, "Estado civil salvo com sucesso!");
            
            TFid.setText(String.valueOf(daoEstado_Civil.buscarProximoId()));
            TFnome.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível salvar o estado civil!");
        }
    }
    
    private void alterar(){
        DaoEstadoCivil daoEstado_Civil = new DaoEstadoCivil();
        
        if (daoEstado_Civil.alterar(Integer.parseInt(TFid.getText()), TFnome.getText())){
            JOptionPane.showMessageDialog(null, "Estado civil alterado com sucesso!");
            
            TFid.setText("");
            TFnome.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível alterar o estado civil!");
        }
        
        ((ListEstado_Civil) Formularios.listEstado_Civil).listarTodos();
        
        dispose();
    }
    
    private void excluir(){
        DaoEstadoCivil daoEstado_Civil = new DaoEstadoCivil();
        
        if (daoEstado_Civil.excluir(Integer.parseInt(TFid.getText()))){
            JOptionPane.showMessageDialog(null, "Estado civil " + TFnome.getText() + " excluído com sucesso!");
            
            TFid.setText("");
            TFnome.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o estado civil!");
        }
        
        ((ListEstado_Civil) Formularios.listEstado_Civil).listarTodos();
        
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        BTacao = new javax.swing.JButton();
        BTexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        TFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        BTacao.setText("Salvar");
        BTacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTacaoActionPerformed(evt);
            }
        });

        BTexcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTexcluir))
                        .addComponent(TFnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTacao)
                    .addComponent(BTexcluir))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFidActionPerformed

    private void BTacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTacaoActionPerformed
        // TODO add your handling code here:
        ListEstado_Civil listEstado_Civil = new ListEstado_Civil();
        if (BTacao.getText() == Constantes.BTN_SALVAR_TEXT){
            inserir();
            
            TFid.setText(String.valueOf(ListEstado_Civil.buscarProximoId()));
            TFnome.setText("");
        }
        else if (BTacao.getText() == Constantes.BTN_ALTERAR_TEXT){
            alterar();
            
            ((ListPais) Formularios.listPais).listarTodos();
            
            dispose();
        }                                     

    
    }//GEN-LAST:event_BTacaoActionPerformed
    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  

        Formularios.cadEstado_Civil = null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEstado_Civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEstado_Civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEstado_Civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEstado_Civil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEstado_Civil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTacao;
    private javax.swing.JButton BTexcluir;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
