/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.Categoria;

import com.mycompany.Ferramentas.Constantes;
import com.mycompany.Ferramentas.DadosTemporarios;
import com.mycompany.Ferramentas.Formularios;
import com.mycompany.Modelo.ModCategoria;
import com.mycompany.Dao.DaoCategoria;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo.3946
 */
public class CadCategoria extends javax.swing.JFrame {

    /**
     * Creates new form cadcategoria
     */
    public CadCategoria() {
        initComponents();
        
        if(!ExisteDadosTemporarios()){
            DaoCategoria daoCategoria = new DaoCategoria();
            
            int id = daoCategoria.buscarProximoId();
            if(id >= 0)
                TFid.setText(String.valueOf(id));
            BTacao.setText(Constantes.BTN_SALVAR_TEXT);
            BTexcluir.setVisible(false);
            
        }else{
            BTacao.setText(Constantes.BTN_SALVAR_TEXT);
            BTexcluir.setVisible(true);
        }
        
        setLocationRelativeTo(null);
        
        TFid.setEnabled(false);
    }
    
    private Boolean ExisteDadosTemporarios(){
        if(DadosTemporarios.tempObject instanceof ModCategoria){
            int id = ((ModCategoria) DadosTemporarios.tempObject).getId();
            String nome = ((ModCategoria) DadosTemporarios.tempObject).getNome();
            String descricao = ((ModCategoria) DadosTemporarios.tempObject).getDescricao();
            
           TFid.setText(String.valueOf(id));
           TFnome.setText(nome);
           TAdescricao.setText(descricao);
        
           DadosTemporarios.tempObject = null;
            
            return true;
        }else
            return false;
    }
    private void inserir(){
        DaoCategoria daoCategoria = new DaoCategoria();
        if (daoCategoria.inserir(Integer.parseInt(TFid.getText()), TFnome.getText(), TAdescricao.getText())){
            JOptionPane.showMessageDialog(null, "Categoria salva com sucesso!");
            
            TFid.setText(String.valueOf(daoCategoria.buscarProximoId()));
            TFnome.setText("");
            TAdescricao.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível salvar a categoria!");
        }
    }
    private void alterar(){
        DaoCategoria daoCategoria = new DaoCategoria();
        
        if (daoCategoria.alterar(Integer.parseInt(TFid.getText()), TFnome.getText(), TAdescricao.getText())){
            JOptionPane.showMessageDialog(null, "Categoria alterada com sucesso!");
            
            TFid.setText("");
            TFnome.setText("");
            TAdescricao.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível alterar a categoria!");
        }
        
        ((ListCategoria) Formularios.listCategoria).listarTodos();
        
        dispose();
    }
    private void excluir(){
        DaoCategoria daoCategoria = new DaoCategoria();
        
        if (daoCategoria.excluir(Integer.parseInt(TFid.getText()))){
            JOptionPane.showMessageDialog(null, "Categoria " + TFnome.getText() + " excluída com sucesso!");
            
            TFid.setText("");
            TFnome.setText("");
            TAdescricao.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível excluir a categoria!");
        }
        
        ((ListCategoria) Formularios.listCategoria).listarTodos();
        
        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAdescricao = new javax.swing.JTextArea();
        BTacao = new javax.swing.JButton();
        BTexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Categoria");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("ID");

        TFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        TFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        TAdescricao.setColumns(20);
        TAdescricao.setRows(5);
        jScrollPane1.setViewportView(TAdescricao);

        BTacao.setText("Salvar");
        BTacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTacaoActionPerformed(evt);
            }
        });

        BTexcluir.setText("Excluir");
        BTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTexcluir))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTacao)
                    .addComponent(BTexcluir))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomeActionPerformed

    private void BTacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTacaoActionPerformed
        // TODO add your handling code here:
        DaoCategoria daoCategoria = new DaoCategoria();
        
        if (BTacao.getText() == Constantes.BTN_SALVAR_TEXT){
            inserir();
            
            TFid.setText(String.valueOf(daoCategoria.buscarProximoId()));
            TFnome.setText("");
            TAdescricao.setText("");
        }
        else if (BTacao.getText() == Constantes.BTN_ALTERAR_TEXT){
            alterar();
            
            ((ListCategoria) Formularios.listCategoria).listarTodos();
            
            dispose();
        }
    }//GEN-LAST:event_BTacaoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        Formularios.cadCategoria = null;
    }//GEN-LAST:event_formWindowClosed

    private void TFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFidActionPerformed

    private void BTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTacao;
    private javax.swing.JButton BTexcluir;
    private javax.swing.JTextArea TAdescricao;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
