/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.Outros.Corporativo;

import com.mycompany.visao.Marca.ListMarca;
import com.mycompany.visao.Marca.CadMarca;
import com.mycompany.Ferramentas.Banco_De_Dados_MySql;
import com.mycompany.Ferramentas.Formularios;
import com.mycompany.visao.Categoria.CadCategoria;
import com.mycompany.visao.Categoria.ListCategoria;
import com.mycompany.visao.Cidade.CadCidade;
import com.mycompany.visao.Cidade.ListCidade;
import com.mycompany.visao.Estado.CadEstado;
import com.mycompany.visao.Estado.ListEstado;
import com.mycompany.visao.Estado_Civil.CadEstado_Civil;
import com.mycompany.visao.Estado_Civil.ListEstado_Civil;
import com.mycompany.visao.Pais.CadPais;
import com.mycompany.visao.Pais.ListPais;
import com.mycompany.visao.Pedido.ListPedido;
import com.mycompany.visao.Pessoa.CadPessoa;
import com.mycompany.visao.Pessoa.ListPessoa;
import com.mycompany.visao.Produto.CadProduto;
import com.mycompany.visao.Produto.ListProduto;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo.3946
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!Banco_De_Dados_MySql.conectar()){
            JOptionPane.showMessageDialog(null, "Não foi possível conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MICadCategoria = new javax.swing.JMenuItem();
        MICadEstadoCivil = new javax.swing.JMenuItem();
        MICadMarca = new javax.swing.JMenuItem();
        MICadPais = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MICadCidade = new javax.swing.JMenuItem();
        MICadEstado = new javax.swing.JMenuItem();
        MICadPessoa = new javax.swing.JMenuItem();
        MICadProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIConCategoria = new javax.swing.JMenuItem();
        MIConEstadoCivil = new javax.swing.JMenuItem();
        MIConMarca = new javax.swing.JMenuItem();
        MIConPais = new javax.swing.JMenuItem();
        MIConCidade = new javax.swing.JMenuItem();
        MIConEstado = new javax.swing.JMenuItem();
        MIConPessoa = new javax.swing.JMenuItem();
        MIConProduto = new javax.swing.JMenuItem();
        MIConPedido = new javax.swing.JMenuItem();

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        MICadCategoria.setText("Categoria");
        MICadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(MICadCategoria);

        MICadEstadoCivil.setText("Estado Civil");
        MICadEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadEstadoCivilActionPerformed(evt);
            }
        });
        jMenu1.add(MICadEstadoCivil);

        MICadMarca.setText("Marca");
        MICadMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadMarcaActionPerformed(evt);
            }
        });
        jMenu1.add(MICadMarca);

        MICadPais.setText("Pais");
        MICadPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadPaisActionPerformed(evt);
            }
        });
        jMenu1.add(MICadPais);
        jMenu1.add(jSeparator1);

        MICadCidade.setText("Cidade");
        MICadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(MICadCidade);

        MICadEstado.setText("Estado");
        MICadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadEstadoActionPerformed(evt);
            }
        });
        jMenu1.add(MICadEstado);

        MICadPessoa.setText("Pessoa");
        MICadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(MICadPessoa);

        MICadProduto.setText("Produto");
        MICadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MICadProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(MICadProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        MIConCategoria.setText("Categoria");
        MIConCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(MIConCategoria);

        MIConEstadoCivil.setText("Estado Civil ");
        MIConEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConEstadoCivilActionPerformed(evt);
            }
        });
        jMenu2.add(MIConEstadoCivil);

        MIConMarca.setText("Marca");
        MIConMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConMarcaActionPerformed(evt);
            }
        });
        jMenu2.add(MIConMarca);

        MIConPais.setText("Pais");
        MIConPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConPaisActionPerformed(evt);
            }
        });
        jMenu2.add(MIConPais);

        MIConCidade.setText("Cidade");
        MIConCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(MIConCidade);

        MIConEstado.setText("Estado");
        MIConEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConEstadoActionPerformed(evt);
            }
        });
        jMenu2.add(MIConEstado);

        MIConPessoa.setText("Pessoa");
        MIConPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(MIConPessoa);

        MIConProduto.setText("Produto");
        MIConProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(MIConProduto);

        MIConPedido.setText("Pedidos");
        MIConPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConPedidoActionPerformed(evt);
            }
        });
        jMenu2.add(MIConPedido);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MICadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadCategoriaActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadCategoria == null)
            Formularios.cadCategoria = new CadCategoria();
        
        Formularios.cadCategoria.setVisible(true);
    }//GEN-LAST:event_MICadCategoriaActionPerformed

    private void MIConCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConCategoriaActionPerformed
        // TODO add your handling code here:
        if (Formularios.listCategoria == null)
            Formularios.listCategoria = new ListCategoria();
        
        Formularios.listCategoria.setVisible(true);
    }//GEN-LAST:event_MIConCategoriaActionPerformed

    private void MICadEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadEstadoCivilActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadEstado_Civil == null)
            Formularios.cadEstado_Civil = new CadEstado_Civil();
        
        Formularios.cadEstado_Civil.setVisible(true);
    }//GEN-LAST:event_MICadEstadoCivilActionPerformed

    private void MIConEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConEstadoCivilActionPerformed
        // TODO add your handling code here:
        if (Formularios.listEstado_Civil == null)
            Formularios.listEstado_Civil = new ListEstado_Civil();
        
        Formularios.listEstado_Civil.setVisible(true);
    }//GEN-LAST:event_MIConEstadoCivilActionPerformed

    private void MICadMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadMarcaActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadMarca == null)
            Formularios.cadMarca = new CadMarca();
        
        Formularios.cadMarca.setVisible(true);
    }//GEN-LAST:event_MICadMarcaActionPerformed

    private void MIConMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConMarcaActionPerformed
        // TODO add your handling code here:
        if (Formularios.listMarca == null)
            Formularios.listMarca = new ListMarca();
        
        Formularios.listMarca.setVisible(true);
    }//GEN-LAST:event_MIConMarcaActionPerformed

    private void MICadPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadPaisActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadPais == null)
            Formularios.cadPais = new CadPais();
        
        Formularios.cadPais.setVisible(true);
    }//GEN-LAST:event_MICadPaisActionPerformed

    private void MIConPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConPaisActionPerformed
        // TODO add your handling code here:
        if (Formularios.listPais == null)
            Formularios.listPais = new ListPais();
        
        Formularios.listPais.setVisible(true);
    }//GEN-LAST:event_MIConPaisActionPerformed

    private void MICadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadCidadeActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadCidade == null)
            Formularios.cadCidade = new CadCidade();
        
        Formularios.cadCidade.setVisible(true);
    }//GEN-LAST:event_MICadCidadeActionPerformed

    private void MIConCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConCidadeActionPerformed
        // TODO add your handling code here:
        if (Formularios.listCidade == null)
            Formularios.listCidade = new ListCidade();
        
        Formularios.listCidade.setVisible(true);
    }//GEN-LAST:event_MIConCidadeActionPerformed

    private void MICadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadEstadoActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadEstado == null)
            Formularios.cadEstado = new CadEstado();
        
        Formularios.cadEstado.setVisible(true);
    }//GEN-LAST:event_MICadEstadoActionPerformed

    private void MIConEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConEstadoActionPerformed
        // TODO add your handling code here:
        if (Formularios.listEstado == null)
            Formularios.listEstado = new ListEstado();
        
        Formularios.listEstado.setVisible(true);
    }//GEN-LAST:event_MIConEstadoActionPerformed

    private void MICadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadPessoaActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadPessoa == null)
            Formularios.cadPessoa = new CadPessoa();
        
        Formularios.cadPessoa.setVisible(true);
    }//GEN-LAST:event_MICadPessoaActionPerformed

    private void MIConPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConPessoaActionPerformed
        // TODO add your handling code here:
        if (Formularios.listPessoa == null)
            Formularios.listPessoa = new ListPessoa();
        
        Formularios.listPessoa.setVisible(true);
    }//GEN-LAST:event_MIConPessoaActionPerformed

    private void MICadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MICadProdutoActionPerformed
        // TODO add your handling code here:
        if (Formularios.cadProduto == null)
            Formularios.cadProduto = new CadProduto();
        
        Formularios.cadProduto.setVisible(true);
    }//GEN-LAST:event_MICadProdutoActionPerformed

    private void MIConProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConProdutoActionPerformed
        // TODO add your handling code here:
        if (Formularios.listProduto == null)
            Formularios.listProduto = new ListProduto();
        
        Formularios.listProduto.setVisible(true);
    }//GEN-LAST:event_MIConProdutoActionPerformed

    private void MIConPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConPedidoActionPerformed
        // TODO add your handling code here:
        if (Formularios.listPedido == null)
            Formularios.listPedido = new ListPedido();
        
       Formularios.listPedido.setVisible(true);
    }//GEN-LAST:event_MIConPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MICadCategoria;
    private javax.swing.JMenuItem MICadCidade;
    private javax.swing.JMenuItem MICadEstado;
    private javax.swing.JMenuItem MICadEstadoCivil;
    private javax.swing.JMenuItem MICadMarca;
    private javax.swing.JMenuItem MICadPais;
    private javax.swing.JMenuItem MICadPessoa;
    private javax.swing.JMenuItem MICadProduto;
    private javax.swing.JMenuItem MIConCategoria;
    private javax.swing.JMenuItem MIConCidade;
    private javax.swing.JMenuItem MIConEstado;
    private javax.swing.JMenuItem MIConEstadoCivil;
    private javax.swing.JMenuItem MIConMarca;
    private javax.swing.JMenuItem MIConPais;
    private javax.swing.JMenuItem MIConPedido;
    private javax.swing.JMenuItem MIConPessoa;
    private javax.swing.JMenuItem MIConProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
