/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.Marca;

import com.mycompany.Ferramentas.Constantes;
import com.mycompany.Ferramentas.DadosTemporarios;
import com.mycompany.Ferramentas.Formularios;
import com.mycompany.Modelo.ModCategoria;
import com.mycompany.Modelo.ModMarca;
import com.mycompany.Dao.DaoCategoria;
import com.mycompany.Dao.DaoMarca;
import com.mycompany.Dao.DaoPais;
import com.mycompany.visao.Categoria.ListCategoria;
import com.mycompany.visao.Pais.ListPais;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo.3946
 */
public class CadMarca extends javax.swing.JFrame {

    /**
     * Creates new form CadMarca
     */
    public CadMarca() {
        initComponents();
        if(!ExisteDadosTemporarios()){
            DaoMarca daoMarca = new DaoMarca();
            
            int id = daoMarca.buscarProximoId();
            if(id >= 0)
                TFid.setText(String.valueOf(id));
            BTacao.setText(Constantes.BTN_SALVAR_TEXT);
            BTexcluir.setVisible(false);
            
        }else{
            BTacao.setText(Constantes.BTN_SALVAR_TEXT);
            BTexcluir.setVisible(true);
        }
        
        setLocationRelativeTo(null);
        
        TFid.setEnabled(false);
    }
    private Boolean ExisteDadosTemporarios(){
        if(DadosTemporarios.tempObject instanceof ModMarca){
            int id = ((ModMarca) DadosTemporarios.tempObject).getId();
            String nome = ((ModMarca) DadosTemporarios.tempObject).getNome();
            
           TFid.setText(String.valueOf(id));
           TFnome.setText(nome);
        
           DadosTemporarios.tempObject = null;
            
            return true;
        }else
            return false;
    }
    private void excluir(){
        DaoMarca daoMarca = new DaoMarca();
        
        if (daoMarca.excluir(Integer.parseInt(TFid.getText()))){
            JOptionPane.showMessageDialog(null, "Marca " + TFnome.getText() + " excluída com sucesso!");
            
            TFid.setText("");
            TFnome.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível excluir a Marca!");
        }
        
        ((ListMarca) Formularios.listMarca).listarTodos();
        
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        BTacao = new javax.swing.JButton();
        BTexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        TFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFidActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        TFnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFnomeActionPerformed(evt);
            }
        });

        BTacao.setText("Salvar");
        BTacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTacaoActionPerformed(evt);
            }
        });

        BTexcluir.setText("Excluir");
        BTexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTexcluir))
                        .addComponent(TFnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTacao)
                    .addComponent(BTexcluir))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFidActionPerformed

    private void TFnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFnomeActionPerformed

    private void BTacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTacaoActionPerformed
        // TODO add your handling code here:
        DaoMarca daoMarca = new DaoMarca();
        if (BTacao.getText() == Constantes.BTN_SALVAR_TEXT){
            inserir();
            
            TFid.setText(String.valueOf(daoMarca.buscarProximoId()));
            TFnome.setText("");
        }
        else if (BTacao.getText() == Constantes.BTN_ALTERAR_TEXT){
            alterar();
            
            ((ListMarca) Formularios.listPais).listarTodos();
            
            dispose();
        }
    }//GEN-LAST:event_BTacaoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {                                  

        Formularios.cadMarca = null;
    }
    private void BTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTacao;
    private javax.swing.JButton BTexcluir;
    private javax.swing.JTextField TFid;
    private javax.swing.JTextField TFnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void inserir() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void alterar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
